export type MatchStrategy = {
  id: string
  label: string
  columns: string[]
  branch: 'zillow' | 'mad' | 'both'
  fuzzy?: boolean
}

export const ZILLOW_STRATEGIES: MatchStrategy[] = [
  {
    id: 'email_company',
    label: 'Email + Company',
    columns: ['Email', 'Company'],
    branch: 'zillow',
  },
  {
    id: 'email',
    label: 'Email',
    columns: ['Email'],
    branch: 'zillow',
  },
  {
    id: 'name_company',
    label: 'Name (fuzzy) + Company',
    columns: ['Name', 'Company'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'website',
    label: 'Website',
    columns: ['Website'],
    branch: 'zillow',
  },
  {
    id: 'phone_name_fuzzy',
    label: 'Phone + Name (fuzzy)',
    columns: ['Phone', 'Name'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'name_exact_email',
    label: 'Name (exact) + Email',
    columns: ['Name', 'Email'],
    branch: 'zillow',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_email',
    label: 'Name (fuzzy) + Email',
    columns: ['Name', 'Email'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'name_exact_phone',
    label: 'Name (exact) + Phone',
    columns: ['Name', 'Phone'],
    branch: 'zillow',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_phone',
    label: 'Name (fuzzy) + Phone',
    columns: ['Name', 'Phone'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'name_company_state',
    label: 'Name (fuzzy) + Company + State',
    columns: ['Name', 'Company', 'Location'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'name_state_fuzzy',
    label: 'Name (fuzzy) + State',
    columns: ['Name', 'Location'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'name_state_exact',
    label: 'Name (exact) + State',
    columns: ['Name', 'Location'],
    branch: 'zillow',
    fuzzy: false,
  },
  {
    id: 'phone',
    label: 'Phone',
    columns: ['Phone'],
    branch: 'zillow',
  },
  {
    id: 'email_state',
    label: 'Email + Location',
    columns: ['Email', 'Location'],
    branch: 'zillow',
  },
  {
    id: 'email_phone',
    label: 'Email + Phone',
    columns: ['Email', 'Phone'],
    branch: 'zillow',
  },
  {
    id: 'name_exact_company',
    label: 'Name (exact) + Company',
    columns: ['Name', 'Company'],
    branch: 'zillow',
    fuzzy: false,
  },
  {
    id: 'name_exact_company_state',
    label: 'Name (exact) + Company + Location',
    columns: ['Name', 'Company', 'Location'],
    branch: 'zillow',
    fuzzy: false,
  },
  {
    id: 'name_exact_email_state',
    label: 'Name (exact) + Email + Location',
    columns: ['Name', 'Email', 'Location'],
    branch: 'zillow',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_email_state',
    label: 'Name (fuzzy) + Email + Location',
    columns: ['Name', 'Email', 'Location'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'name_exact_phone_state',
    label: 'Name (exact) + Phone + Location',
    columns: ['Name', 'Phone', 'Location'],
    branch: 'zillow',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_phone_state',
    label: 'Name (fuzzy) + Phone + Location',
    columns: ['Name', 'Phone', 'Location'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'website_state',
    label: 'Website + Location',
    columns: ['Website', 'Location'],
    branch: 'zillow',
  },
  {
    id: 'website_name_fuzzy',
    label: 'Website + Name (fuzzy)',
    columns: ['Website', 'Name'],
    branch: 'zillow',
    fuzzy: true,
  },
  {
    id: 'website_name_exact',
    label: 'Website + Name (exact)',
    columns: ['Website', 'Name'],
    branch: 'zillow',
    fuzzy: false,
  },
]

export const MAD_STRATEGIES: MatchStrategy[] = [
  {
    id: 'email',
    label: 'Email',
    columns: ['Email'],
    branch: 'mad',
  },
  {
    id: 'phone',
    label: 'Phone',
    columns: ['Phone'],
    branch: 'mad',
  },
  {
    id: 'name_exact_email',
    label: 'Name (exact) + Email',
    columns: ['Name', 'Email'],
    branch: 'mad',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_email',
    label: 'Name (fuzzy) + Email',
    columns: ['Name', 'Email'],
    branch: 'mad',
    fuzzy: true,
  },
  {
    id: 'name_exact_phone',
    label: 'Name (exact) + Phone',
    columns: ['Name', 'Phone'],
    branch: 'mad',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_phone',
    label: 'Name (fuzzy) + Phone',
    columns: ['Name', 'Phone'],
    branch: 'mad',
    fuzzy: true,
  },
  {
    id: 'name_state_exact',
    label: 'Name (exact) + State',
    columns: ['Name', 'Location'],
    branch: 'mad',
    fuzzy: false,
  },
  {
    id: 'name_state_fuzzy',
    label: 'Name (fuzzy) + State',
    columns: ['Name', 'Location'],
    branch: 'mad',
    fuzzy: true,
  },
  {
    id: 'name_exact',
    label: 'Name (exact)',
    columns: ['Name'],
    branch: 'mad',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy',
    label: 'Name (fuzzy)',
    columns: ['Name'],
    branch: 'mad',
    fuzzy: true,
  },
  {
    id: 'email_phone',
    label: 'Email + Phone',
    columns: ['Email', 'Phone'],
    branch: 'mad',
  },
  {
    id: 'email_state',
    label: 'Email + Location',
    columns: ['Email', 'Location'],
    branch: 'mad',
  },
  {
    id: 'phone_state',
    label: 'Phone + Location',
    columns: ['Phone', 'Location'],
    branch: 'mad',
  },
  {
    id: 'name_exact_email_state',
    label: 'Name (exact) + Email + Location',
    columns: ['Name', 'Email', 'Location'],
    branch: 'mad',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_email_state',
    label: 'Name (fuzzy) + Email + Location',
    columns: ['Name', 'Email', 'Location'],
    branch: 'mad',
    fuzzy: true,
  },
  {
    id: 'name_exact_phone_state',
    label: 'Name (exact) + Phone + Location',
    columns: ['Name', 'Phone', 'Location'],
    branch: 'mad',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_phone_state',
    label: 'Name (fuzzy) + Phone + Location',
    columns: ['Name', 'Phone', 'Location'],
    branch: 'mad',
    fuzzy: true,
  },
  {
    id: 'name_exact_email_phone',
    label: 'Name (exact) + Email + Phone',
    columns: ['Name', 'Email', 'Phone'],
    branch: 'mad',
    fuzzy: false,
  },
  {
    id: 'name_fuzzy_email_phone',
    label: 'Name (fuzzy) + Email + Phone',
    columns: ['Name', 'Email', 'Phone'],
    branch: 'mad',
    fuzzy: true,
  },
]

export const DEFAULT_ZILLOW_CONFIG: string[] = [
  'email_company',
  'email',
  'name_exact_email',
  'name_fuzzy_email',
  'name_company',
  'website',
  'name_exact_phone',
  'name_fuzzy_phone',
  'phone_name_fuzzy',
  'name_company_state',
  'name_state_fuzzy',
  'name_state_exact',
]

export const DEFAULT_MAD_CONFIG: string[] = [
  'email',
  'name_exact_email',
  'name_fuzzy_email',
  'phone',
  'name_exact_phone',
  'name_fuzzy_phone',
  'name_state_exact',
  'name_state_fuzzy',
  'name_exact',
  'name_fuzzy',
]
